development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:8d00a2da162da7fb8a481f92eac45967@pike.redistogo.com:11086" } %>
  channel_prefix: chat_app_production
